/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_pkg;

import class_pkg.*;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class GUI_principal extends javax.swing.JFrame {

    LinkedList<ClientClass> clientObjectList = new LinkedList<>();
    LinkedList<accountClass> accountObjectList = new LinkedList<>();
    LinkedList<CreditcardClass> creditcardObjectList = new LinkedList<>();
    LinkedList<productClass> productObjectList = new LinkedList<>();

    /**
     * Creates new form GUI_principal
     */
    public GUI_principal() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_client_name = new javax.swing.JTextField();
        txt_client_addres = new javax.swing.JTextField();
        txt_client_phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_client_email = new javax.swing.JTextField();
        btn_add_account = new javax.swing.JButton();
        txt_user_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_credit_Card_number = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_credit_Card_Balance = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_credit_Card_holder = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_product_name = new javax.swing.JTextField();
        txt_product_cost = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_add_products = new javax.swing.JButton();
        btn_show_products = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_product_stock = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        product_list = new javax.swing.JList<>();
        jLabel19 = new javax.swing.JLabel();
        txt_product_id = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accounts_list = new javax.swing.JList<>();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_confirm_changes = new javax.swing.JButton();
        txt_new_balance = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_actual_balance = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        list_type_pedido = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txt_search_pedido = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btn_searpedido = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txt_cant_producto = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_resultado_pedido = new javax.swing.JLabel();
        btn_confirmar_pedido = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_costo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Direccion");

        jLabel3.setText("Telefono");

        jLabel7.setText("Correo Electronico");

        btn_add_account.setText("Registro");
        btn_add_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_accountActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre de usuario");

        jLabel4.setText("Credit Card Number");

        jLabel6.setText("Credit Card Balance");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Crear Cuenta de usuario");

        jLabel11.setText("Credit Card Holder");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(298, 298, 298))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_client_phone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_client_addres, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_client_email)
                            .addComponent(txt_client_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_user_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_credit_Card_number, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_credit_Card_Balance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_credit_Card_holder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btn_add_account)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_credit_Card_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_client_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_credit_Card_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txt_credit_Card_holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_client_addres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_client_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_client_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(45, 45, 45)
                .addComponent(btn_add_account)
                .addGap(84, 84, 84))
        );

        jTabbedPane1.addTab("Registro Usuarios", jPanel1);

        jLabel8.setText("Valor Producto");

        jLabel9.setText("Nombre de producto");

        btn_add_products.setText("Añadir Productos");
        btn_add_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_productsActionPerformed(evt);
            }
        });

        btn_show_products.setText("Mostar Productos");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Productos");

        jLabel12.setText("Stock Producto");

        jScrollPane2.setViewportView(product_list);

        jLabel19.setText("id produto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_product_stock, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(txt_product_cost, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(txt_product_name, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(txt_product_id))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel13))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btn_add_products)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_show_products)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel13)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_product_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_product_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_product_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_products)
                    .addComponent(btn_show_products))
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lista de Productos", jPanel3);

        jScrollPane1.setViewportView(accounts_list);

        btn_search.setText("Buscar");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel14.setText("Nombre de usuario:");

        jLabel15.setText("Blance Actual:");

        btn_confirm_changes.setText("Confirmar");
        btn_confirm_changes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirm_changesActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Ver cuenta");

        txt_actual_balance.setText(" ");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Balance Actual");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(btn_search)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(jLabel16))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(txt_actual_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_new_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_confirm_changes)
                        .addGap(71, 71, 71)))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_search)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addGap(19, 19, 19)
                        .addComponent(txt_actual_balance)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_new_balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_confirm_changes)
                        .addGap(112, 112, 112)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Detalles Cuenta", jPanel2);

        list_type_pedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pedido Simple", "Pedido Compuesto" }));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Realizar Pedidos");

        jLabel20.setText("Digite el id del producto");

        btn_searpedido.setText("Buscar");
        btn_searpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searpedidoActionPerformed(evt);
            }
        });

        jLabel21.setText("Cant de Producto");

        jLabel22.setText("Tipo de pedido");

        txt_resultado_pedido.setText(" ");

        btn_confirmar_pedido.setText("Confirmar");
        btn_confirmar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmar_pedidoActionPerformed(evt);
            }
        });

        jLabel23.setText("nombre de usuario");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Costo total");

        jLabel25.setText(" ");

        txt_costo.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_resultado_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txt_search_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_searpedido))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel17)))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(18, 18, 18)
                            .addComponent(txt_cant_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel22)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_costo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(list_type_pedido, 0, 208, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_confirmar_pedido)
                .addGap(112, 112, 112))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_search_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_searpedido)
                    .addComponent(txt_cant_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_resultado_pedido)
                    .addComponent(jLabel23)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(21, 21, 21)
                .addComponent(list_type_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txt_costo))
                .addGap(18, 18, 18)
                .addComponent(btn_confirmar_pedido)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Realizar Pedido", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_productsActionPerformed
        // TODO add your handling code here:
        try {
            int product_id = Integer.parseInt(txt_product_id.getText());
            String product_name = txt_product_name.getText();
            int product_price = Integer.parseInt(txt_product_cost.getText());
            int product_stock = Integer.parseInt(txt_product_stock.getText());
            if (product_name.equals("") || product_price == 0 || product_stock == 0) {
                JOptionPane.showMessageDialog(this, "Complete todos lo campos para continuar");
            } else {
                productClass product = new productClass(product_id, product_name, product_stock, product_price);
                productObjectList.add(product);
                clearfieldsproducts();
                show_products();
                JOptionPane.showMessageDialog(this, "Producto agregado con exito");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar producto");
        }
    }//GEN-LAST:event_btn_add_productsActionPerformed

    private void btn_add_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_accountActionPerformed
        // TODO add your handling code here:
        try {
            String user_name = txt_user_name.getText();
            String client_name = txt_client_name.getText();
            String client_address = txt_client_addres.getText();
            String client_phone = txt_client_phone.getText();
            String client_email = txt_client_email.getText();
            int credit_card_number = Integer.parseInt(txt_credit_Card_number.getText());
            String credit_card_holder = txt_credit_Card_holder.getText();
            int credit_card_balance = Integer.parseInt(txt_credit_Card_Balance.getText());
            if (user_name.equals("") || client_name.equals("") || client_address.equals("")
                    || client_address.equals("") || client_phone.equals("") || client_email.equals("")
                    || credit_card_holder.equals("") || credit_card_balance == 0) {
                JOptionPane.showMessageDialog(this, "Complete todos lo campos para continuar");
            } else {
                accountClass account = new accountClass(client_name, client_address, client_phone, client_email, user_name, credit_card_balance, credit_card_number);
                accountObjectList.add(account);
                ClientClass client = new ClientClass(client_name, client_address, client_phone, client_email);
                clientObjectList.add(client);
                CreditcardClass creditcard = new CreditcardClass(credit_card_number, credit_card_holder, credit_card_balance);
                creditcardObjectList.add(creditcard);
                clearfieldsaccount();
                show_acconunt();
                JOptionPane.showMessageDialog(this, "Cuenta creada con exito");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear la cuenta");
        }
    }//GEN-LAST:event_btn_add_accountActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        String user_name = txt_search.getText();
        boolean find_pet = false;
        for (accountClass account : accountObjectList) {
            if (user_name.equals(account.getUser_name())) {
                //consulta valor existente
                txt_actual_balance.setText(Integer.toString(account.getAccount_balance()));

                break;
            }
            if (!find_pet) {
                JOptionPane.showMessageDialog(this, "No se encontro ninguna cuenta con el nombre de usuario suministradi");
            }
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_confirm_changesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirm_changesActionPerformed
        // TODO add your handling code here:
        String user_name = txt_search.getText();
        boolean find_pet = false;
        for (accountClass account : accountObjectList) {
            if (user_name.equals(account.getUser_name())) {
                //consulta valor existente
                //txt_actual_balance.setText(Integer.toString(account.getAccount_balance()));
                //actualiza el valor
                int new_balance = Integer.parseInt(txt_new_balance.getText());
                account.setAccount_balance(new_balance);
                show_acconunt();
                find_pet = true;

                break;
            }
            if (!find_pet) {
                JOptionPane.showMessageDialog(this, "No se encontro ninguna cuenta con el nombre de usuario suministrado");
            }
        }
    }//GEN-LAST:event_btn_confirm_changesActionPerformed

    private void btn_searpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searpedidoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txt_search_pedido.getText());
        boolean find_pet = false;
        for (productClass product : productObjectList) {
            if (id == (product.getProduct_id())) {
                //consulta valor existente
                txt_resultado_pedido.setText(product.getProduct_id() + "-" + product.getName() + "-" + product.getCost() + "-" + product.getStock());

                break;
            }
            if (!find_pet) {
                JOptionPane.showMessageDialog(this, "No se encontro ningun producto con el id suministrado");
            }
        }
    }//GEN-LAST:event_btn_searpedidoActionPerformed

    private void btn_confirmar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmar_pedidoActionPerformed
        // TODO add your handling code here:
        int cant_producto = Integer.parseInt(txt_cant_producto.getText());
        String user_name = txt_username.getText();
        String type_request = list_type_pedido.getSelectedItem().toString();
        int balance_account = 0;
        int id_producto = Integer.parseInt(txt_product_id.getText());
        int total = 0;
        boolean find_pet = false;
        if (type_request.equals("Pedido Simple") || cant_producto <= 20) {
            JOptionPane.showMessageDialog(this, "Un pedido simple solo puede realizar una compra max de 20 unidades");
            for (accountClass account : accountObjectList) {
                if (user_name.equals(account.getUser_name())) {
                    //consulta valor existente
                    balance_account = account.getAccount_balance();
                    for (productClass producto : productObjectList) {
                        if (id_producto == producto.getProduct_id()) {
                            total = cant_producto * producto.getCost();
                            if (balance_account < total) {
                                JOptionPane.showMessageDialog(this, "No posee fondos suficientes para realizar la compra");
                            } else {
                                txt_costo.setText("El costo total es de: " + total);
                                int new_balance = balance_account - total;
                                account.setAccount_balance(new_balance);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "no se encontro un producto registrado con este id");
                        }
                    }

                    break;
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontro ninguna cuenta con el nombre de usuario suministrado");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "El pedido posee una cantidad mayor a las 20 unidades, se actualizara a pedido compuesto");
            for (accountClass account : accountObjectList) {
                if (user_name.equals(account.getUser_name())) {
                    //consulta valor existente
                    balance_account = account.getAccount_balance();
                    for (productClass producto : productObjectList) {
                        if (id_producto == producto.getProduct_id()) {
                            total = cant_producto * producto.getCost();
                            if (balance_account < total) {
                                JOptionPane.showMessageDialog(this, "No posee fondos suficientes para realizar la compra");
                            } else {
                                txt_costo.setText("El costo total es de: " + total);
                                int new_balance = balance_account - total;
                                account.setAccount_balance(new_balance);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "no se encontro un producto registrado con este id");
                        }
                    }

                    break;
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontro ninguna cuenta con el nombre de usuario suministrado");
                }
            }
        }
    }//GEN-LAST:event_btn_confirmar_pedidoActionPerformed
    public void show_products() {
        DefaultListModel products_list = new DefaultListModel();
        int index_list = 0;
        for (productClass product : productObjectList) {
            String registro_products = product.getName() + " - " + "$" + product.getCost() + " - " + product.getStock() + " unds";
            products_list.add(index_list, registro_products);
            index_list++;
        }
        product_list.setModel(products_list);
    }

    public void show_acconunt() {
        DefaultListModel account_list = new DefaultListModel();
        int index_list = 0;
        for (accountClass account : accountObjectList) {
            String registro_accounts = account.getUser_name() + " - " + account.getName() + " - " + account.getEmail() + " - " + account.getPhone() + "-" + account.getAddress() + " - " + account.getCard_number() + " - " + account.getAccount_balance();
            account_list.add(index_list, registro_accounts);
            index_list++;
        }
        accounts_list.setModel(account_list);
    }

    public void clearfieldsaccount() {
        txt_user_name.setText("");
        txt_client_addres.setText("");
        txt_client_email.setText("");
        txt_client_name.setText("");
        txt_client_phone.setText("");
        txt_credit_Card_Balance.setText("");
        txt_credit_Card_holder.setText("");
        txt_credit_Card_number.setText("");
    }

    public void clearfieldsproducts() {
        txt_product_cost.setText("");
        txt_product_name.setText("");
        txt_product_stock.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> accounts_list;
    private javax.swing.JButton btn_add_account;
    private javax.swing.JButton btn_add_products;
    private javax.swing.JButton btn_confirm_changes;
    private javax.swing.JButton btn_confirmar_pedido;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_searpedido;
    private javax.swing.JButton btn_show_products;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> list_type_pedido;
    private javax.swing.JList<String> product_list;
    private javax.swing.JLabel txt_actual_balance;
    private javax.swing.JTextField txt_cant_producto;
    private javax.swing.JTextField txt_client_addres;
    private javax.swing.JTextField txt_client_email;
    private javax.swing.JTextField txt_client_name;
    private javax.swing.JTextField txt_client_phone;
    private javax.swing.JLabel txt_costo;
    private javax.swing.JTextField txt_credit_Card_Balance;
    private javax.swing.JTextField txt_credit_Card_holder;
    private javax.swing.JTextField txt_credit_Card_number;
    private javax.swing.JTextField txt_new_balance;
    private javax.swing.JTextField txt_product_cost;
    private javax.swing.JTextField txt_product_id;
    private javax.swing.JTextField txt_product_name;
    private javax.swing.JTextField txt_product_stock;
    private javax.swing.JLabel txt_resultado_pedido;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_search_pedido;
    private javax.swing.JTextField txt_user_name;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
